apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: statusquarkusio-qlvc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: statusquarkusio-qlvc
    app.kubernetes.io/part-of: status-quarkus-io
  name: statusquarkusio-qlvc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: statusquarkusio-qlvc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: statusquarkusio-qlvc
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-nddp-tenant/status-quarkus-io/statusquarkusio-qlvc@sha256:dd9249e55d10a8e63af39fda4f6712e2d0cc724701c7a4ec1bfff519cfbc0d8a
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
